### ISSUE TITLE
あとがきの「Rubyのコミュニティ」に 地域Rubyの会 へのリンクをつけてはどうでしょう

### ISSUE THREAD

**Issue by snoozer05** [igaiga/rails_textbook#14]
> 近くのRubyコミュニティの集まりへぜひ足を運んでみてください

か

> Rubyコミュニティは「都市名.rb」という名前で活動していることが多いです。

のあたりが https://github.com/ruby-no-kai/official/wiki/RegionalRubyistMeetUp とうまく接続されていると、読者が「お近くのRubyコミュニティ」を探しやすくなるんじゃないかと思いました。

**Comment by igaiga** [comment]
追記しました！ご意見ありがとうございました！ :sunflower: 
https://github.com/igaiga/rails_textbook/commit/88d7c961ac5168cb543d61ea9a16b3c847e9f7ad
