### ISSUE TITLE
校正支援のためtextlintを導入しませんか

### ISSUE THREAD

**Issue by takahashim** [igaiga/rails_textbook#5]
最近textlintという校正支援ツールを試してみているのですが、Railsの教科書でも使ってみませんか？

https://github.com/textlint/textlint

各種ルールをプラグインで突っ込んで使うタイプのツールで、ルールの調整はもろもろ必要になるかと思います。あと、JavaScript製のツールなのでpackage.json等を導入する必要があります。

**Comment by igaiga** [comment]
@takahashim おー！ESLintのmarkdown版なんですね。いいと思います。時間あるときに触ってみますね。
jsに疎いのですが、js版のbundler+Gemfileみたいなものいれて、環境を作れるようにするのがいいのかな？それともインストール方法をREADMEに書いて、ルールファイルだけ管理した方が楽かな・・・。ほかのプロジェクトでの運用ノウハウがもしあったら教えてください。

**Comment by takahashim** [comment]
@igaiga まだ実験的に試してるだけで、ちゃんと運用してるのはないのでした。
とりあえずファイルの方を用意して、「npm test」で実行できるようにしてみます。
安定したらTravis CIでコミットごとに実行できるようにしてみてもよいかもです。

**Comment by igaiga** [comment]
@takahashim 了解です！ファイルありがとうございます！出力調整はたいへんそうですね、、、

**Comment by takahashim** [comment]
commitしたのでこちらは閉じておきます
