### ISSUE TITLE
p.114 誤記報告

### ISSUE THREAD

**Issue by wisteria2gp** [igaiga/rails_textbook#53]
PDF版を拝読させていただいています。

  第７章p114、本文(コードの後)1文目に

> ⽣成されたmigration ファイルには、books テーブルへauthor カラムをstring 型で追加する指⽰が書かれています。

とありますが、文脈的にauthor->pictureの誤りだと思います。

**Comment by igaiga** [comment]
ご報告ありがとうございます！ 😃 
次の版で修正させていただきます。
